<?php

/**
 * @file
 * Module file for industry things.
 */

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for grants_industries module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;

const GRANTS_INDUSTRIES_GID = 123;

/**
 * Implements hook_form_alter().
 */
function grants_industries_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'user_form') {
    $currentUser = \Drupal::currentUser();
    $roles = $currentUser->getRoles();
    if (!in_array(['admin', 'grants_admin'], $roles)) {
      $form["field_industry"]["#disabled"] = TRUE;
    }
  }

}

/**
 * Implements hook_node_access_records().
 */
function grants_industries_node_access_records(NodeInterface $node) {
  // Let's add custom grant for selected industry in service page nodes.
  if ($node->getType() === 'service') {
    // Get selected field value.
    $industry = $node->get('field_industry')->value;
    // Create realm string.
    $industry_realm = 'grants_industry_' . $industry;
    // Create grants for this industry on this node.
    // This means that in hook_node_grants below we can then add proper grant
    // for user when checking their permissions.
    $grants[] = [
      'realm' => $industry_realm,
      'gid' => GRANTS_INDUSTRIES_GID,
      'grant_view' => 1,
      'grant_update' => 1,
      'grant_delete' => 0,
    ];
    return $grants;
  }
}

/**
 * Implements hook_node_grants().
 */
function grants_industries_node_grants(AccountInterface $account, $op) {
  $grants = [];
  // Work on updates, otherwise leave as is set up in general permissions.
  if ($op == 'update') {
    // Get user roles.
    $userRoles = $account->getRoles();
    // Check that user has industry producer role.
    if (in_array('content_producer_industry', $userRoles)) {
      // Load user object.
      $userObject = User::load($account->id());
      // Get user's industry selection.
      foreach ($userObject->field_industry as $userIndustryField) {
        $userIndustry = $userIndustryField->value;
        if ($userIndustry) {
          // If we have set industry for user.
          $industry_realm = 'grants_industry_' . $userIndustry;
          // Add this realm for this user.
          $grants[$industry_realm] = GRANTS_INDUSTRIES_GID;
        }
      }
    }
  }
  return $grants;
}

/**
 * Implements hook_openid_connect_post_authorize().
 */
function grants_industries_openid_connect_post_authorize(UserInterface $account, array $context) {

  // If user has AD groups.
  if (isset($context["user_data"]["ad_groups"]) && !empty($context["user_data"]["ad_groups"])) {

    Drupal::logger('grants_industries')->debug('User @username, AdGroups: @adgroups',['@username' => $account->getAccountName(),'@adgroups' => Json::encode($context["user_data"]["ad_groups"])]);

    $industryKeys = [];
    // Loop them.
    foreach ($context["user_data"]["ad_groups"] as $ad_group) {
      $industryKey = '';
      $ad_group_lower = strtolower($ad_group);
      // @todo remove in prod
      if (str_contains($ad_group_lower, 'owakayttajat')) {
        $industryKey = 'KUVA';
      }
      if (str_contains($ad_group_lower, 'kanslia_kayttajat')) {
        $industryKey = 'KANSLIA';
      }
      // If user has one of the designated groups, set the industry key.
      if (str_contains($ad_group_lower, 'ta_kuva')) {
        $industryKey = 'KUVA';
      }
      if (str_contains($ad_group_lower, 'ta_kasko')) {
        $industryKey = 'KASKO';
      }
      if (str_contains($ad_group_lower, 'pk_pel')) {
        $industryKey = 'PEL';
      }
      if (str_contains($ad_group_lower, 'ta_kymp')) {
        $industryKey = 'KYMP';
      }
      if (str_contains($ad_group_lower, 'ta_sote')) {
        $industryKey = 'SOTE';
      }
      if ($industryKey != '') {
        $industryKeys[] = $industryKey;
      }
    }
    // If we have industry key && user has this field.
    if ($account->hasField('field_industry') && !empty($industryKeys)) {
      // Set field value.
      $account->set('field_industry', $industryKeys);
      try {
        // And try to save account.
        $account->save();
      }
      catch (Exception $e) {
        \Drupal::logger('grants_industries')->error($e->getMessage());
      }
    }
  }

}
