<?php

/**
 * @file
 * Provides an example of a webform handler.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function grants_handler_theme() {
  return [
    'webform_handler_grants_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
  ];
}

/**
 * Implements hook_webform_element_alter().
 */
function grants_handler_webform_element_alter(
  array &$element,
  FormStateInterface $form_state,
  array $context) {


//  if (isset($element['#webform_id']) &&
//    $element['#webform_id'] === 'yleisavustushakemus--account_number') {
//    $element['#element_validate'][] = [
//      'Drupal\grants_profile\Plugin\Validation\Constraint\ValidIbanValidator',
//      'validate'
//    ];
//  }

}
