<?php

namespace Drupal\grants_profile\Plugin\DataType;

use Drupal\Core\TypedData\Plugin\DataType\Map;
use Symfony\Component\Validator\ConstraintViolationListInterface;

/**
 * Address DataType.
 *
 * @DataType(
 * id = "grants_profile_profile",
 * label = @Translation("Grants Profile"),
 * definition_class =
 *   "\Drupal\grants_profile\TypedData\Definition\GrantsProfileDefinition"
 * )
 */
class GrantsProfileData extends Map {

  /**
   * {@inheritdoc}
   */
  public function setValue($values, $notify = TRUE) {

    if ($values['companyStatusSpecial'] == NULL) {
      $values['companyStatusSpecial'] = '';
    }

    foreach ($values as $key => $value) {
      if ($key == 'bankAccounts') {
        foreach ($value as $key2 => $bankAccount) {
          if (
            is_array($bankAccount['confirmationFile']) && empty($bankAccount['confirmationFile'])) {
            $values[$key][$key2]['confirmationFile'] = '';
          }
          elseif (isset($bankAccount['confirmationFile'])) {
            $values[$key][$key2]['confirmationFile'] = $bankAccount['confirmationFile'];
          }
        }
      }

    }

    // @todo Change the autogenerated stub
    parent::setValue($values, $notify);
  }

  /**
   * This is where we could validate custom fields, bank accounts etc.
   */
  public function validate(): ConstraintViolationListInterface {
    $parentResults = parent::validate();

    return $parentResults;
  }

}
