<?php

/**
 * @file
 * Allows webforms to be shared on other websites using an iframe.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\webform\WebformInterface;
use Drupal\grants_webform_print\GrantsWebformPrintPreRender;
use Drupal\grants_webform_print\GrantsWebformPrintHelper;

function grants_webform_print_preprocess_webform_container_base_html(&$variables) {
  if ($variables['element']['#type'] == 'webform_section') {
    $variables['element']['#attributes']['class'][] = "webform-preview-inner-section";
  }
  if ($variables['element']['#type'] == 'webform_wizard_page') {
    $variables['value']['#type'] = 'webform_section';
    unset($variables['value']['#open']);
    $variables['element']['#type'] = 'webform_section';
    $variables['element']['#webform_plugin_id'] = 'webform_section';
  }
}

/**
 * Implements hook_element_info_alter().
 */
function grants_webform_print_element_info_alter(&$type) {
  $type['page']['#pre_render'][] = [GrantsWebformPrintPreRender::class, 'page'];
}

/**
 * Implements hook_block_access().
 */
function grants_webform_print_block_access(Block $block, $operation, AccountInterface $account) {
  if (!GrantsWebformPrintHelper::isPage()) {
    return AccessResult::neutral();
  }

  // Only adjust block view access.
  if ($operation !== 'view') {
    return AccessResult::neutral();
  }

  // Hide all blocks to improve the webform share page's performance.
  return AccessResult::forbidden();
}

/**
 * Implements hook_page_top().
 */
function grants_webform_print_page_top(array &$page_top) {
  if (!GrantsWebformPrintHelper::isPage()) {
    return;
  }
  // Remove the toolbar from the webform print page.
  unset($page_top['toolbar']);
}

/******************************************************************************/
// Theme functions.
/******************************************************************************/

/**
 * Implements hook_theme().
 */
function grants_webform_print_theme($existing, $type, $theme, $path) {
  return [
    // Using dedicated html and page template ensures the shared webforms
    // output is as simple as possible.
    'html__grants_webform_print' => [
      'render element' => 'html',
    ],
    'page__grants_webform_print' => [
      'render element' => 'page',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function grants_webform_print_theme_suggestions_html(array $variables) {
  return (GrantsWebformPrintHelper::isPage()) ? ['html__grants_webform_print'] : [];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function grants_webform_print_theme_suggestions_page(array $variables) {
  return (GrantsWebformPrintHelper::isPage()) ? ['page__grants_webform_print'] : [];
}

/**
 * Prepares variables for the webform share page HTML templates.
 */
function template_preprocess_html__grants_webform_print(&$variables) {
  // Make sure the variables are preprocessed.
  // @see template_preprocess_page()
  if (!isset($variables['page'])) {
    template_preprocess_html($variables);
  }

  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = \Drupal::routeMatch()->getParameter('webform');

  // Add html.webform-share-page-html class.
  $variables['html_attributes']->addClass('webform-print-page-html');

  // Add body.webform-share-page-body class.
  // @see grants_webform_print.page.css
  $variables['attributes'] += ['class' => []];
  $variables['attributes']['class'][] = 'webform-print-page-body';

  // Remove toolbar.module body classes.
  // @see toolbar_preprocess_html()
  if (\Drupal::currentUser()->hasPermission('access toolbar')) {
    foreach ($variables['attributes']['class'] as $index => $class_name) {
      if (strpos($class_name, 'toolbar-') === 0) {
        unset($variables['attributes']['class'][$index]);
      }
    }
    $variables['attributes']['class'] = array_values($variables['attributes']['class']);
  }
}

/**
 * Prepares variables for the webform share page templates.
 */
function template_preprocess_page__grants_webform_print(&$variables) {
  // Make sure the variables are preprocessed.
  // @see template_preprocess_page()
  if (!isset($variables['base_path'])) {
    template_preprocess_page($variables);
  }
}

/**
 * Implements hook_preprocess_HOOK() for page title templates.
 */
function grants_webform_print_preprocess_page_title(&$variables) {
  if (!GrantsWebformPrintHelper::isPage()) {
    return;
  }

  // Remove shortcut widget from page title.
  // @see shortcut_preprocess_page_title()
  if (isset($variables['title_suffix'])) {
    unset($variables['title_suffix']['add_or_remove_shortcut']);
  }
}
