<?php

/**
 * @file
 * Allows webforms to be shared on other websites using an iframe.
 */

/**
 * Implements hook_theme().
 */
function grants_webform_print_theme($existing, $type, $theme, $path) {
  return [
    'grants_webform_print_webform' => [
      'render element' => 'build',
      'variables' => [
        'content' => NULL,
        'webform' => NULL,
      ],
    ],
    'webform_submission_form__grants_webform_print' => [
      'render element' => 'page',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grants_webform_print_preprocess_webform_progress_tracker(&$variables) {
  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = $variables['webform'];
  /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
  $webform_submission = $variables['webform_submission'];

  $pages = $webform->getPages($variables['operation'], $webform_submission);
  // Get the logged errors for the form.
  /** @var \Drupal\grants_handler\GrantsHandlerNavigationHelper $grants_formnavigation_helper */
  $grants_formnavigation_helper = \Drupal::service('grants_handler.navigation_helper');

  // Get all errors.
  $all_errors = $grants_formnavigation_helper->getAllErrors($webform_submission);

  $currentPageVariables = $variables["current_page"];

  // Iterate through the pages and set appropriate page classes.
  foreach ($pages as $key => $page) {

    // Add the default class for the page.
    $variables['page_classes'][$key][] = 'progress-step';

    $hasVisitedThisPage = $grants_formnavigation_helper->hasVisitedPage(
      $webform_submission,
      $key
    );

    if ($hasVisitedThisPage) {
      $variables['page_classes'][$key][] = 'has-visited';
    }
    else {
      $variables['page_classes'][$key][] = 'not-visited';
    }

    // Add the visited and error classes if it has been logged.
    if ((isset($all_errors[$key]) && !empty($all_errors[$key]))) {
      // Add an error class if the page has errors or complete class if not.
      $variables['page_classes'][$key][] = 'has-errors';
    }

    // Add an active class to the current page.
    if ($currentPageVariables == $key) {
      $variables['page_classes'][$key][] = 'is-active';
    }
    elseif (is_array($all_errors)) {
      if ($hasVisitedThisPage && isset($all_errors[$key]) && empty($all_errors[$key])) {
        $variables['page_classes'][$key][] = 'is-complete';
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grants_webform_print_preprocess_webform_progress_bar(&$variables) {
  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = $variables['webform'];
  /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
  $webform_submission = $variables['webform_submission'];

  $pages = $webform->getPages($variables['operation'], $webform_submission);
  // Get the logged errors for the form.
  /** @var \Drupal\grants_handler\GrantsHandlerNavigationHelper $grants_formnavigation_helper */
  $grants_formnavigation_helper = \Drupal::service('grants_handler.navigation_helper');

  $current_errors = $grants_formnavigation_helper->getAllErrors($webform_submission);

  // Iterate through the pages and set appropriate page classes.
  foreach ($pages as $key => $page) {
    // Add the default class for the page.
    $variables['page_classes'][$key][] = 'webform-progress-bar__page';
    // Add the visited and error classes if it has been logged.
    if (isset($current_errors[$key])) {
      // Add an error class if the page has errors or complete class if not.
      $variables['page_classes'][$key][] = empty($current_errors[$key]) ? 'webform-progress-bar__page--done' : 'webform-progress-bar__page--errors';
    }
    // Add an active class to the current page.
    if ($variables['current_page'] == $key) {
      $variables['page_classes'][$key][] = 'webform-progress-bar__page--current';
    }
  }
}
