<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 *
 */
function grants_metadata_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_settings_form' || $form_id == 'webform_add_form' || $form_id == 'webform_duplicate_form') {
    $bundle = $form_state->getFormObject()->getEntity();
    // Because hidden by default.
    $form["third_party_settings"]["#access"] = TRUE;
    $form['third_party_settings']['#tree'] = TRUE;

    $form['third_party_settings']['grants_metadata'] = [
      '#type' => 'details',
      '#title' => t('Application details'),
      '#open' => TRUE,
      '#input' => FALSE,
    ];

    $form['third_party_settings']['grants_metadata']['applicationType'] = [
      '#type' => 'textfield',
      '#title' => t('Application Type'),
      '#default_value' => $bundle->getThirdPartySetting('grants_metadata', 'applicationType'),
      '#required' => TRUE,
    ];

    $form['third_party_settings']['grants_metadata']['applicationTypeID'] = [
      '#type' => 'textfield',
      '#title' => t('Application Type ID'),
      '#default_value' => $bundle->getThirdPartySetting('grants_metadata', 'applicationTypeID'),
      '#required' => TRUE,
    ];
  }
}
