<?php

/**
 * @file
 * Primary module hooks for Oma Asiointi module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function grants_oma_asiointi_theme() {
  $theme['grants_oma_asiointi_block'] = [
    'render element' => 'build',
    'variables' => [
      'messages' => NULL,
      'submissions' => NULL,
      'userProfileData' => NULL,
      'applicationTypes' => NULL,
      'lang' => NULL,
    ],
  ];

  return $theme;
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function grants_oma_asiointi_preprocess_block(&$vars) {
  if($vars["plugin_id"] == 'grants_oma_asiointi_block') {
    //-- This stops the block being cache in drupal 8
    $vars['#cache']['max-age'] = 0;
  }
}