<?php

/**
 * @file
 * Primary module hooks for Oma Asiointi module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function grants_oma_asiointi_theme() {
  $theme['grants_oma_asiointi_block'] = [
    'render element' => 'build',
    'variables' => [
      'messages' => NULL,
      'submissions' => NULL,
      'userProfileData' => NULL,
      'applicationTypes' => NULL,
      'lang' => NULL,
    ],
  ];
  $theme['grants_oma_asiointi_front'] = [
    'render element' => 'build',
    'variables' => [
      'title' => NULL,
      'drafts' => NULL,
      'others' => NULL,
      'unread' => NULL,
    ],
  ];

  return $theme;
}

/**
 * Implements hook_page_attachments().
 */
function grants_oma_asiointi_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'grants_oma_asiointi/grants_oma_asiointi';
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function grants_oma_asiointi_preprocess_block(&$vars) {
  if ($vars["plugin_id"] == 'grants_oma_asiointi_block') {
    // -- This stops the block being cache in drupal 8
    $vars['#cache']['max-age'] = 0;
  }
}

/**
 * Implements hook_preprocess().
 */
function grants_oma_asiointi_preprocess_page_title(&$variables) {
  $variables['initials'] = 'AS';
  $variables['colorscheme'] = '0';
}

/**
 * Implements hook_views_pre_build().
 */
function grants_oma_asiointi_views_pre_build(ViewExecutable $view) {
  // Only operate on ukk view.
  if ($view->id() == 'ukk') {
    // Get the url query parameter.
    $selected = \Drupal::request()->query->get('ukk');
    // If we don't have one set.
    if (!$selected) {
      // Load all terms form ukk kats.
      $terms = \Drupal::entityTypeManager()
        ->getStorage('taxonomy_term')
        ->loadTree('ukk_kategoriat');
      $filterValueToSet = 0;
      // Set first value as selected.
      foreach ($terms as $term) {
        $filterValueToSet = (int) $term->tid;
        break;
      }
      // Only use this if we have terms.
      if ($filterValueToSet != 0) {
        $view->setExposedInput(['ukk' => $filterValueToSet]);
      }
    }
  }
}
