<?php

/**
 * @file
 * Primary module hooks for Oma Asiointi module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function grants_oma_asiointi_theme() {
  $theme['grants_oma_asiointi_block'] = [
    'render element' => 'build',
    'variables' => [
      'messages' => NULL,
      'submissions' => NULL,
      'userProfileData' => NULL,
      'applicationTypes' => NULL,
      'lang' => NULL,
    ],
  ];
  $theme['grants_oma_asiointi_front'] = [
    'render element' => 'build',
    'variables' => [
      'title' => NULL,
      'drafts' => NULL,
      'others' => NULL,
      'unread' => NULL,
    ],
  ];

  return $theme;
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function grants_oma_asiointi_preprocess_block(&$vars) {
  if($vars["plugin_id"] == 'grants_oma_asiointi_block') {
    //-- This stops the block being cache in drupal 8
    $vars['#cache']['max-age'] = 0;
  }
}

/**
 * Implements hook_preprocess().
 */
function grants_oma_asiointi_preprocess_page_title(&$variables) {
  $variables['initials'] = 'AS';
  $variables['colorscheme'] = 'green';
}

/**
 * Implements hook_preprocess().
 */
function grants_oma_asiointi_preprocess_views_view_unformatted(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  $viewId = $view->id();
  if ($viewId == 'haettavat_avustukset') {
    $result = $view->result;
    $d = 'af';
  }
}

/**
 * Implements hook_theme().
 */
function grants_oma_asiointi_preprocess_views_view_fields__haettavat_avustukset__block(&$variables) {
  $d = 'asdf';
}

/**
 * Implements hook_theme().
 */
function grants_oma_asiointi_preprocess_paragraphs_summary(&$variables) {
  $d = 'asdf';
}

