<?php

/**
 * @file
 * Primary module hooks for Grants Profile module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function grants_profile_theme(): array {
  $theme['view_application'] = [
    'render element' => 'build',
    'variables' => [
      'application' => NULL,
      'document' => NULL,
    ]
  ];
  $theme['own_profile'] = [
    'render element' => 'build',
    'variables' => [
      'content' => NULL,
      'company_select_form' => NULL,
      'profile' => NULL
    ]
  ];
  $theme['own_addresses'] = [
    'render element' => 'build',
    'variables' => [
      'addresses' => NULL
    ]
  ];
  $theme['application_officials'] = [
    'render element' => 'build',
    'variables' => [
      'officials' => NULL
    ]
  ];
  $theme['bank_accounts'] = [
    'render element' => 'build',
    'variables' => [
      'bank_accounts' => NULL
    ]
  ];

  return $theme;
}
