<?php

/**
 * @file
 * Primary module hooks for grants_mandate module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_preprocess_html().
 */
function grants_mandate_preprocess_html(&$variables) {
  if ('grants_mandate.mandateform' === \Drupal::routeMatch()->getRouteName()) {
    $variables['html_attributes']['class'] = 'page--select-applicant-role';
  }
}
